/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_viveris_jnidbus_bindings_bus_Connection */

#ifndef _Included_fr_viveris_jnidbus_bindings_bus_Connection
#define _Included_fr_viveris_jnidbus_bindings_bus_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_viveris_jnidbus_bindings_bus_Connection
 * Method:    createConnection
 * Signature: (Lfr/viveris/jnidbus/BusType;Ljava/lang/String;Ljava/lang/String;)Lfr/viveris/jnidbus/bindings/bus/Connection;
 */
JNIEXPORT jobject JNICALL Java_fr_viveris_jnidbus_bindings_bus_Connection_createConnection
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     fr_viveris_jnidbus_bindings_bus_Connection
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fr_viveris_jnidbus_bindings_bus_Connection_closeNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
