package fr.viveris.vizada.jnidbus.serialization;

/**
 * In order to reduce the overhead of JNI code, serialized object are put in an intermediate representation easier to parse
 * by the JNI code. This class is the intermediate representation.
 *
 * The structure is very basic, we only have a string representing the DBus signature and a raw Object array which contains
 * all the message data. A DBusObject can contains other DbusObject if the signature contains nested objects. Lists are
 * represented as an Object array.
 *
 * When serialized, each DBusObject contain the correct DBus signature, when unserializing, only the root object contains
 * the correct signature. This dur to libdbus limitations, the correct signature will eb applied during the process using
 * the Signature object generated by the root object.
 *
 * Warning for maintainers: this object is heavily used by JNI code, be careful when modifying it
 */
public class DBusObject {

    /**
     * Dbus signature string
     */
    private String signature;

    /**
     * raw values following the signature
     */
    private Object[] values;

    public DBusObject(String signature, Object[] values) {
        this.signature = signature;
        this.values = values;
    }

    public String getSignature(){
        return this.signature;
    }

    public Object[] getValues(){
        return this.values;
    }
}
